environment:
  matrix:
    - nodejs_version: "6"
install:
  - ps: Install-Product node $env:node_version
  - yarn
  - yarn bootstrap
matrix:
  fast_finish: true
build: off
cache:
  - "%LOCALAPPDATA%\\Yarn"
test_script:
  - node --version
  - yarn --version
  - yarn test
